### ISSUE TITLE
Integration just adds 4 entities

### ISSUE THREAD

**Issue by drivingmx** [elupus/hass_nibe#106]
When I set up the integration, just 4 entities appear: Hot water, ventilation, S1 Room, S1 Supply.
In former integrations, i was used to have a lot more sensors. (all sensors, that the uplink portal shows)

My configuration: 
```
nibe:
  systems:
    - system: 85810
      units:
        - unit: 0
```

Do I need to configure all sensors by naming them in the config.yaml? Is there a list or a "add all" configuration?
