### ISSUE TITLE
S1_supply entity is unavailable

### ISSUE THREAD

**Issue by tomrennen** [elupus/hass_nibe#122]
I have a Nibe BA-SVM 10-200 combined with an F2040. My `climate.nibe_xxxxx_s1_supply` is always unavailable, could there be a parsing error? Or does my heatpump not expose the right parameters perhaps? I'm primarily looking for a way to distinguish which operation is currently running (Room heating/cooling, water heating). Nibe uplink GUI doesn't provide me with info regarding the operation mode either, so I'm not very hopeful. I have access to the api using postman, so I can provide you the json if you need it.

My config for reference:
``` yaml
nibe:
  # Default client identifier
  client_id: xxx

  # Default client secret
  client_secret: xxx

  # Default redirect url
  redirect_uri: 'https://xxx/api/nibe/auth'
```
