### ISSUE TITLE
nable to prepare setup for platform nibe.climate: Platform not found

### ISSUE THREAD

**Issue by bortek** [elupus/hass_nibe#140]
Getting this error looks like it does not understand some of the attribute names? Any ideas?

I dont have anyt fan btw my pump is F1255

2022-08-09 22:08:57 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform nibe.climate: Platform not found (cannot import name 'ClimateEntityFeature' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
2022-08-09 22:08:57 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.nibe.sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/nibe/sensor.py", line 137, in <module>
device_class=SensorDeviceClass.DURATION,
File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
raise AttributeError(name) from None
AttributeError: DURATION
2022-08-09 22:08:57 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform nibe.sensor: Platform not found (Exception importing custom_components.nibe.sensor).
2022-08-09 22:08:57 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform nibe.fan: Platform not found (cannot import name 'FanEntityFeature' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).

My config looks like this but even if I remove all that config I still get the same error.

```yaml
nibe:
  # Default client identifier
  client_id: REMOVED

  # Default client secret
  client_secret: REMOVED

  # Default redirect url
  redirect_uri: 'http://localhost:8123/api/nibe/auth'

  systems:
    # System identifier to add extra entities too
    - system: REMOVED
```
