### ISSUE TITLE
[F750] Boost preset sets fan to 0%

### ISSUE THREAD

**Issue by jonkristian** [elupus/hass_nibe#148]
Selecting boost preset results in my ventilation being set to 0%.
Same happens also via my automation which used to work fine.

```
service: fan.set_preset_mode
target:
  entity_id: fan.nibe_83039_ventilation
data:
  preset_mode: boost
```
