### ISSUE TITLE
Power consumption sensors not configured properly to be added to energy dashboard

### ISSUE THREAD

**Issue by marcusthorstrom** [elupus/hass_nibe#154]
I have a Nibe F750 and it has two sensors:

* sensor.nibe_XXXXX_43144 - compressor time factor
* sensor.nibe_XXXXX_43305 - compressor time factor hot water

Both of these report in kwh:

```YAML
state_class: measurement
designation: ''
parameter_id: 43144
display_value: 4954.7kWh
raw_value: 495468
display_unit: kWh
unit_of_measurement: kWh
device_class: energy
friendly_name: compressor time factor
```
and
```YAML
state_class: measurement
designation: ''
parameter_id: 43305
display_value: 769.3kWh
raw_value: 76928
display_unit: kWh
unit_of_measurement: kWh
device_class: energy
friendly_name: compressor time factor hot water

```

When I try to add these to the engergy dashboard it says:

> The following entities have state class 'measurement' but 'last_reset' is missing:

![image](https://user-images.githubusercontent.com/6585553/199671139-99d17762-f136-4375-841c-9ed9b39ec1f5.png)

I understand this could be fixed by just setting the `state_class` to `total_increasing` [(reference)](https://community.home-assistant.io/t/energy-dashboard-last-reset-missing/406733/8)

By browsing the code, one suggestion is to set the `state_class` to `total_increasing` when the `unit_of_measurement` is kWh.

/Marcus
