### ISSUE TITLE
defrost history problem

### ISSUE THREAD

**Issue by SzymaneKwr** [elupus/hass_nibe#157]
the sensor.nibe_91210_44703 entity does not show any data in history.
![2022-11-30_13h26_27](https://user-images.githubusercontent.com/77275930/204799950-91e4549e-b439-4004-8c67-39c82d5c4ac7.png)

**Comment by NickSutton** [comment]
It would be very helpful if this entity could report something useful. Is it just a case of setting the unit_of_measurement value  to a string?

**Comment by elupus** [comment]
the sensor_class also need to be set to measurement. I wonder why it has no unit.

**Comment by NickSutton** [comment]
Spot on, in fact just adding `sensor_class: measurement` in the dev tools then plotted the graph properly.

I'm going to have a go at using [Customize Entity to temporarily fix the issue: ](https://www.home-assistant.io/docs/configuration/customizing-devices/)

````
  customize:
    # Add an entry for each entity that you want to overwrite.
    sensor.nibe_XXXXXX_44703:
      sensor_class: measurement
````
