### ISSUE TITLE
Optional smart thermostats in the config file - what's the goal?

### ISSUE THREAD

**Issue by stphndrnd** [elupus/hass_nibe#34]
Hey,

I see this in the README.md

```
# Optional smart thermostats.
          thermostats:
            # Key in dict is external identifer in nibe uplink, it should
            # be an unique integer for this thermostat
            1:
              # Required friendly name of thermostat
              name: "Kitchen Thermostat"

              # Optional name of a home assistant entity representing current temperature
              current_temperature: input_number.current

              # Optional name of a home assistant entity representing valve position of
              # a thermostat. At the moment it's use case is unknown.
              # valve_position: input_number.valve

              # List of systems that this thermostat is affecting. This is
              # this is the sub climate system/area index (System 1, System 2, ..)
              # that the pump is controlling.
              systems: 1
```

What is the exact purpose of it? Will it create a smart thermostat the same way the nibe.set_thermostat function works? If so why aren't all the available parameters for this function available in the config file? i.e. I miss the target_temperature parameter.

Thanks!
