### ISSUE TITLE
No Fan Speed

### ISSUE THREAD

**Issue by outrun0506** [elupus/hass_nibe#83]
Hi,

first of all, thanks for this incredible Integration.
I'm all setup and Data a coming into Homeassistant.

What I'm missing, is the current FanSpeed.
I own a Nibe AMS 10-12 / F2040

3 Fan Sensor are created, but everyone has as Status - Not available

Here's my Config

```yaml
nibe:
  systems:
    - system: "XXXXXXX"
      units:
        - unit: 0
          categories: true
          statuses: true
      climates: true
      water_heaters: true
      fans: true
      sensors:
        - 40004
        - 47264
        - 47265
        - 10001
        - fan_speed
```

Any hints on this?

**Comment by elupus** [comment]
Did you get the fan entities (not the extra sensors you added manually)?

**Comment by outrun0506** [comment]
Should this be Exhaust Fan speed 1? If yes, this Entity also has status not available.

**Comment by elupus** [comment]
No. There should have been created a entity with entity id: "fan.xxxxx" i don't remember how the friendly name would end up.

**Comment by outrun0506** [comment]
Well yes, there a free entities with Fan speed. But everyone has the state unavailable.

**Comment by elupus** [comment]
And these are not the sensor entities you added? 40004, 47264, 47265? 

Can you give me a screenshot from the state under developer tool/states?

**Comment by outrun0506** [comment]
For sure,

i remove the "custom" Sensors from the Integration.

My current Config:

```yaml
nibe:
  systems:
    - system: "98885"
      units:
        - unit: 0
          categories: true
          statuses: true
      climates: true
      water_heaters: true
      fans: true
#      sensors:
#        - 47264
#        - 47265
#        - 10001
#        - fan_speed
```
But no sensor was remove from HA (not a problem, i can do this manualy)

Hmm, but as you mentioned, the entities looks like, they where generated from the 4 extra sensor i put in my config.

Here are the requestes screenshots:

![image](https://user-images.githubusercontent.com/23034252/105607627-172e6880-5da0-11eb-965c-aa6e74fc97e9.png)
![image](https://user-images.githubusercontent.com/23034252/105607630-1eee0d00-5da0-11eb-93ad-079d4fcaabb7.png)
![image](https://user-images.githubusercontent.com/23034252/105607633-231a2a80-5da0-11eb-95ba-ad683f32422e.png)


Does this mean, my heat pump is not reporting a Fanspeed via the API?

BR and Thanks for the helping Hand
Lukas

**Comment by elupus** [comment]
you should be looking at the entity called. fan.nibe_* it should be there

**Comment by elupus** [comment]
You enable more logging for the integration by adding the following to your logs section in homeassistant (https://www.home-assistant.io/integrations/logger/)
```
nibeuplink: debug
custom_components.nibe.fan: debug
custom_components.nibe debug
```

**Comment by elupus** [comment]
Btw. Do you see a fan speed when you look at https://nibeuplink.com ?

**Comment by outrun0506** [comment]
> Btw. Do you see a fan speed when you look at https://nibeuplink.com ?

Yes i see the fanspeed.

Debug Info are coming later on.

**Comment by elupus** [comment]
Btw. Are you on discord? https://discord.gg/c5DvZ4e pm me there. Might be quicker.

**Comment by outrun0506** [comment]
Just to sum up this issue as @elupus helped me on discord:

My heatpump has no fan, it uses a compressor in slave1 (you can find this out at https://nibeuplink.com)

![image](https://user-images.githubusercontent.com/23034252/105609001-9a52bd00-5da6-11eb-8043-2c326568a677.png)

for adding slave1 as additional sensors you have to add another unit to your config (unit 1).

My config now looks like:

```yaml
nibe:
  systems:
    - system: "98885"
      units:
        - unit: 0
          categories: true
          statuses: true
        - unit: 1
          categories: true
          statuses: true
      climates: true
      water_heaters: true
      fans: false
```

Thanks @elupus for clarify this topic!

BR
Lukas
