### ISSUE TITLE
Error getting temperature from climate

### ISSUE THREAD

**Issue by cschroer** [elupus/hass_nibe#86]
Hi,

thanks for the integration. I'm trying to set it up with a NIBE VVM 320 E + F2040-12. I'm also using the KNX integration to get most of my smart home components know to Home Assistant.

The integration itself works as a charm, I'm able to get all the data from my heating system.

Creating a thermostat fails, heres what I do configure:
```yaml
thermostats:
   1:
     # friendly name of thermostat
     name: 'Büro 1'
     current_temperature: climate.buro_1
     valve_position: sensor.buro_1_ventil
     systems: 1
```

The climate itself is in state `heat` with the following attributes:
```yaml
hvac_modes:
  - heat
min_temp: 15
max_temp: 27
target_temp_step: 0.5
preset_modes: []
current_temperature: 21.4
temperature: 21
preset_mode: null
friendly_name: Büro 1
supported_features: 17
```

the sensor for the ventil is in state `0` with the following attribues:
```yaml
unit_of_measurement: '%'
friendly_name: Büro 1 - Ventil
```

When adding the thermostat I get an error fromt he component:

> 2021-02-10 19:43:33 ERROR (MainThread) [custom_components.nibe.climate] Unable to update from sensor: could not convert string to float: 'heat'

From my understanding this is correct, as the state of `climate.buro_1` is heat. The current temperature should be fetched from the attributes?
